name: Generate Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup checkout
      uses: actions/checkout@master
    - name: Install uv
      uses: astral-sh/setup-uv@main
    - name: execute notebooks
      run: |
        uv run --extra docs --pre --python 3.10 --pre python -m ipykernel install --name dacapo_env --user
        uv run --extra docs --pre --python 3.10 jupytext --to notebook --execute tutorials/minimal_tutorial.py
        mv tutorials/minimal_tutorial.ipynb docs/source/notebooks/
    - name: Build documentation
      run: uv run --extra docs --pre --python 3.10 sphinx-build docs/source docs/build/html -b html

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/build/html
        retention-days: 90

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4