name: Generate Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: Setup checkout
      uses: actions/checkout@master
    - name: Install uv
      uses: astral-sh/setup-uv@main
    - name: Install pandoc
      uses: pandoc/actions/setup@v1
      with:
        version: 2.19
    - name: install ffmpeg
      run: sudo apt-get install ffmpeg
    - name: execute notebooks
      run: |
        uv run --extra docs --pre --python 3.11 python -m ipykernel install --name dacapo_env --user
        uv run --extra docs --pre --python 3.11 jupytext --to notebook tutorials/dataset/dataset_overview.py
        uv run --extra docs --pre --python 3.11 jupytext --to notebook tutorials/dataset/dataset_training.py
        cp -r tutorials docs/source
    - name: Build documentation
      run: uv run --extra docs --pre --python 3.11 sphinx-build docs/source docs/build/html -b html
    - name: Set permissions
      run: chmod -R a+rX ./docs/build/html
    - name: Update gh branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html