name: Python mypy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  static-analysis:
    name: Python mypy
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: mypy
        run: |
          uv run --pre --extra dev mypy
